
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Oct 01 20:57:43 COT 2021
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Extern = 4;
  public static final int Op_atribucion = 47;
  public static final int Parentesis_c = 57;
  public static final int Return = 37;
  public static final int Op_booleano = 54;
  public static final int Parentesis_a = 56;
  public static final int Llave_c = 59;
  public static final int Llave_a = 58;
  public static final int Std = 71;
  public static final int Linea = 73;
  public static final int Break = 27;
  public static final int Coma = 64;
  public static final int Corchete_c = 38;
  public static final int Corchete_a = 8;
  public static final int Long = 12;
  public static final int Punto = 63;
  public static final int Default = 34;
  public static final int Print = 28;
  public static final int Char = 5;
  public static final int Comillas_S = 6;
  public static final int For = 24;
  public static final int Else = 21;
  public static final int Resta = 32;
  public static final int Int = 2;
  public static final int Gets = 30;
  public static final int Nulo = 36;
  public static final int Suma = 52;
  public static final int Using = 69;
  public static final int ERROR = 53;
  public static final int Cadena = 18;
  public static final int Typedef = 67;
  public static final int Main = 60;
  public static final int Do = 22;
  public static final int T_datoN = 17;
  public static final int Op_relacional = 46;
  public static final int P_coma = 61;
  public static final int Unsigned = 40;
  public static final int Short = 13;
  public static final int Case = 26;
  public static final int Const = 14;
  public static final int Continue = 10;
  public static final int S = 51;
  public static final int Numeral = 55;
  public static final int Sistema = 41;
  public static final int Vacio = 7;
  public static final int If = 20;
  public static final int Define = 49;
  public static final int Dos_P = 62;
  public static final int EOF = 0;
  public static final int toString = 72;
  public static final int Numero = 68;
  public static final int Double = 11;
  public static final int Struct = 15;
  public static final int Division = 9;
  public static final int Scan = 29;
  public static final int Namespace = 70;
  public static final int error = 1;
  public static final int Comillas = 16;
  public static final int Enum = 33;
  public static final int SizeOf = 42;
  public static final int Identificador = 65;
  public static final int Op_incremento = 48;
  public static final int Include = 19;
  public static final int Modulo = 44;
  public static final int Fgets = 31;
  public static final int Register = 66;
  public static final int Igual = 43;
  public static final int Goto = 3;
  public static final int While = 23;
  public static final int Union = 35;
  public static final int Op_logico = 45;
  public static final int B_Slash = 39;
  public static final int Multiplicacion = 50;
  public static final int Switch = 25;
}

