/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Analizador;



public enum Tokens {
    Int,
    Linea,
    Comillas,
    Comillas_S,
    B_Slash,
    T_datoN,
    Cadena,
    Char,
    Vacio,
    Nulo,
    Include,
    If,
    Else,
    Do,
    While,
    For,
    Switch,
    Case,
    Break,
    Const,
    Continue,
    Enum,
    Extern,
    Goto,
    Long,
    Union,
    Struct,
    Default,
    Print,
    Scan,
    Gets,
    Fgets,
    Return,
    Unsigned,
    Sistema,
    SizeOf,
    Igual,
    Suma,
    Resta,
    Multiplicacion,
    Division,
    Modulo,
    Op_logico,
    Op_relacional,
    Op_atribucion,
    Op_incremento,
    Op_booleano,
    Numeral,
    Parentesis_a,
    Parentesis_c,
    Llave_a,
    Llave_c,
    Corchete_a,
    Corchete_c,
    Main,
    Register,
    P_coma,
    Dos_P,
    Punto,
    Coma,
    Identificador,
    Numero,
    Typedef,
    ERROR   
}
